// import React from "react";
// import sonaliImage from "../../assets/sonali.jpg";
// import Image from "next/image";

// function page() {
//     const branchName = "DAULATGONJ CUMILLA";
//     const branchAddress = "13136 - DAULATGONJ CUMILLA CUMILLA";

//     const data = [
//         {
//             date: "01-Jul-2024",
//             valueDate: "31-Dec-2024",
//             originatingBranch: "Laksam",
//             transaction: "Cash Withdrawal INST NUM SB13136857372",
//             debit: "6500",
//             credit: "",
//             balance: "6500",
//         },
//     ];
//     return (
//         <div className="container mx-auto p-5 w-[1150px] h-screen">
//             <div className="flex flex-row gap-4 justify-between">
//                 <div>
//                     <Image src={sonaliImage} alt="logo" className="w-48 h-14" />
//                     <p className="text-xs">Generated By</p>
//                     <p className="text-sm">{branchName}</p>
//                     <p className="text-sm">{branchAddress}</p>
//                 </div>
//                 <div className="space-y-2 text-sm">
//                     <p>
//                         <span className="font-bold">Print Date</span>{" "}
//                         01-Jul-2024
//                     </p>
//                     <p>
//                         <span className="font-bold">Print time</span> 11:09 AM
//                     </p>
//                     <p>
//                         <span className="font-bold">User ID</span> 46238
//                     </p>
//                 </div>
//             </div>

//             <div>
//                 <p className="text-center mt-4 font-bold">
//                     STATEMENT OF ACCOUNT
//                 </p>
//                 <table className="w-full border border-black text-sm">
//                     <tbody>
//                         <tr>
//                             <td className="py-2 px-3 border-r border-black align-top w-1/2">
//                                 <p className="font-bold pb-3">MD KABIR KHAN</p>
//                                 <p>VILL- RAMPUR,</p>
//                                 <p>POST-UTTARDA,</p>
//                                 <p>LAKSAM,</p>

//                                 <p>COMILLA</p>
//                             </td>

//                             <td className=" px-3 align-top w-1/2 leading-4.5">
//                                 <p>
//                                     <span className="font-bold">Branch :</span>{" "}
//                                     {branchAddress}
//                                 </p>
//                                 <p>
//                                     <span className="font-bold">
//                                         Currency :
//                                     </span>{" "}
//                                     BDT
//                                 </p>
//                                 <p>
//                                     <span className="font-bold">
//                                         Account Number :
//                                     </span>{" "}
//                                     13124551542415
//                                 </p>
//                                 <p className="font-bold">
//                                     Account Type : SB - Savings Bank Account
//                                     (General)
//                                 </p>
//                                 <p>
//                                     <span className="font-bold">Period :</span>{" "}
//                                     01-Jul-2024 - 31-Dec-2024
//                                 </p>
//                                 <p>
//                                     <span className="font-bold">Status :</span>{" "}
//                                     Active
//                                 </p>
//                                 <p>
//                                     <span className="font-bold">
//                                         Touting Number :
//                                     </span>{" "}
//                                     200191548
//                                 </p>
//                             </td>
//                         </tr>
//                     </tbody>
//                 </table>
//             </div>

//             {/* Statement Table */}
//             <div className="mt-10">
//                 <table className="w-full text-sm table-auto">
//                     <thead>
//                         <tr>
//                             <th className="border px-1.5 py-1 text-center w-28">
//                                 Date
//                             </th>
//                             <th className="border px-1.5 py-1 text-center w-28">
//                                 Value Date
//                             </th>
//                             <th className="border text-left px-1.5 py-1 w-64">
//                                 Originating Branch
//                             </th>
//                             <th className="border text-left px-1.5 py-1 w-68">
//                                 Transaction
//                             </th>
//                             <th className="border px-1.5 py-1 text-right w-32">
//                                 Debit
//                             </th>
//                             <th className="border px-1.5 py-1 text-right w-32">
//                                 Credit
//                             </th>
//                             <th className="border px-1.5 py-1 text-right w-44">
//                                 Balance
//                             </th>
//                         </tr>
//                     </thead>
//                     <tbody className="text-xs align-top">
//                         <tr>
//                             <td className="border px-1.5 py-1 text-center"></td>
//                             <td className="border px-1.5 py-1 text-center"></td>
//                             <td className="border px-1.5 py-1 text-left"></td>
//                             <td className="border px-1.5 py-1 text-left">
//                                 Opening Balance
//                             </td>
//                             <td className="border px-1.5 py-1 text-right"></td>
//                             <td className="border px-1.5 py-1 text-right"></td>
//                             <td className="border px-1.5 py-1 text-right">
//                                 6506.00 cr
//                             </td>
//                         </tr>
//                         {data.map((item, index) => (
//                             <tr key={index}>
//                                 <td className="border px-1.5 py-1 text-center">
//                                     {item.date}
//                                 </td>
//                                 <td className="border px-1.5 py-1 text-center">
//                                     {item.valueDate}
//                                 </td>
//                                 <td className="border text-left px-1.5 py-1 uppercase align-middle">
//                                     {item.originatingBranch}
//                                 </td>
//                                 <td className="border text-left px-1.5">
//                                     {item.transaction}
//                                 </td>
//                                 <td className="border px-1.5 py-1 text-right">
//                                     {Number(item.debit).toFixed(2)}
//                                 </td>
//                                 <td className="border px-1.5 py-1 text-right">
//                                     {Number(item.credit).toFixed(2)}
//                                 </td>
//                                 <td className="border px-1.5 py-1 text-right">
//                                     {Number(item.balance).toFixed(2)} cr
//                                 </td>
//                             </tr>
//                         ))}
//                         <tr>
//                             <td className=" px-1.5 py-1 text-center"></td>
//                             <td className=" px-1.5 py-1 text-center"></td>
//                             <td className=" text-left px-1.5 py-1 uppercase align-middle"></td>
//                             <td className="px-1.5 font-bold text-right">
//                                 Total
//                             </td>
//                             <td className=" px-1.5 py-1 text-right">6500.00</td>{" "}
//                             {/* Sum of debit balance */}
//                             <td className=" px-1.5 py-1 text-right">
//                                 0.00
//                             </td>{" "}
//                             {/* Sum of credit balance */}
//                             <td className=" px-1.5 py-1 text-right"></td>
//                             <td className=" px-1.5 py-1 text-right"></td>
//                         </tr>
//                     </tbody>
//                 </table>
//             </div>
//         </div>
//     );
// }

// export default page;

"use client";

import { PDFViewer } from "@react-pdf/renderer";
import StatementPDF from "@/components/StatementPDF";

const PdfViewerPage = () => {
    const transactions = [
        {
            date: "03-Jun-2024",
            valueDate: "03-Jun-2024",
            originatingBranch: "Local Office, Dhaka",
            transaction:
                "BEFTN AUTO 202406037712286 TREASURY SINGLE ACCOUNT-3000183-BB: MOTIJHEEL L PAD",
            debit: "",
            credit: "50,590.81",
            balance: "16,78,480.37",
        },
        {
            date: "13-Jun-2024",
            valueDate: "13-Jun-2024",
            originatingBranch: "HEAD OFFICE",
            transaction: "Ewallet A2A-BEFTN To:1202632800210 296759851",
            debit: "1,00,000.00",
            credit: "",
            balance: "15,78,480.37",
        },
        {
            date: "20-Jun-2024",
            valueDate: "20-Jun-2024",
            originatingBranch: "",
            transaction: "Statement Charge",
            debit: "100.00",
            credit: "",
            balance: "15,78,380.37",
        },
        {
            date: "20-Jun-2024",
            valueDate: "20-Jun-2024",
            originatingBranch: "",
            transaction: "VAT On Statement Charge",
            debit: "15.00",
            credit: "",
            balance: "15,78,385.37",
        },
        {
            date: "20-Jun-2024",
            valueDate: "20-Jun-2024",
            originatingBranch: "",
            transaction: "Cash Withdrawal INST NUM SB13136857380",
            debit: "30,000.00",
            credit: "",
            balance: "15,48,365.37",
        },
        {
            date: "28-Jun-2024",
            valueDate: "28-Jun-2024",
            originatingBranch: "",
            transaction: "Maintenance Charge",
            debit: "250.00",
            credit: "",
            balance: "15,48,115.37",
        },
        {
            date: "28-Jun-2024",
            valueDate: "28-Jun-2024",
            originatingBranch: "",
            transaction: "VAT On Maintenance Charge For Product 1000",
            debit: "38.00",
            credit: "",
            balance: "15,48,077.37",
        },
        {
            date: "28-Jun-2024",
            valueDate: "28-Jun-2024",
            originatingBranch: "",
            transaction: "SMS Charged(Transactional Alert)",
            debit: "50.00",
            credit: "",
            balance: "15,48,027.37",
        },
        {
            date: "28-Jun-2024",
            valueDate: "28-Jun-2024",
            originatingBranch: "",
            transaction: "SMS Charge VAT(Transactional Alert)",
            debit: "8.00",
            credit: "",
            balance: "15,48,019.37",
        },
        {
            date: "28-Jun-2024",
            valueDate: "28-Jun-2024",
            originatingBranch: "",
            transaction: "SMS Charged(Push Pull)",
            debit: "50.00",
            credit: "",
            balance: "15,47,969.37",
        },
        {
            date: "28-Jun-2024",
            valueDate: "28-Jun-2024",
            originatingBranch: "",
            transaction: "SMS Charge VAT(Push Pull)",
            debit: "8.00",
            credit: "",
            balance: "15,47,961.37",
        },
        {
            date: "29-Jun-2024",
            valueDate: "29-Jun-2024",
            originatingBranch: "HEAD OFFICE",
            transaction: "Ewallet A2A-BEFTN To:1202632800210 296759851",
            debit: "1,50,000.00",
            credit: "",
            balance: "13,97,961.37",
        },
        {
            date: "29-Jun-2024",
            valueDate: "29-Jun-2024",
            originatingBranch: "HEAD OFFICE",
            transaction: "Ewallet A2A-BEFTN To:1202632800210 296759851",
            debit: "50,000.00",
            credit: "",
            balance: "13,47,961.37",
        },
        {
            date: "30-Jun-2024",
            valueDate: "30-Jun-2024",
            originatingBranch: "",
            transaction: "Interest Applied",
            debit: "",
            credit: "7,379.00",
            balance: "13,55,340.37",
        },
        {
            date: "30-Jun-2024",
            valueDate: "30-Jun-2024",
            originatingBranch: "",
            transaction: "TDS Deduction On Interest Amount",
            debit: "1,107.00",
            credit: "",
            balance: "13,54,233.37",
        },
        {
            date: "02-Jul-2024",
            valueDate: "02-Jul-2024",
            originatingBranch: "",
            transaction: "BEFTN",
            debit: "",
            credit: "50,406.12",
            balance: "14,04,639.49",
        },
        {
            date: "14-Jul-2024",
            valueDate: "14-Jul-2024",
            originatingBranch: "",
            transaction: "Repayment Of 1313648000699",
            debit: "22,810.00",
            credit: "",
            balance: "13,81,829.49",
        },
        {
            date: "01-Aug-2024",
            valueDate: "01-Aug-2024",
            originatingBranch: "",
            transaction:
                "BEFTN Transfer 2024080119508611 TREASURY SINGLE ACCOUNT-3000183386 TREASURY SINGLE-BB: MOTIJHEEL L PAD",
            debit: "",
            credit: "47,798.58",
            balance: "14,29,628.07",
        },
        {
            date: "12-Aug-2024",
            valueDate: "12-Aug-2024",
            originatingBranch: "",
            transaction: "Cash Withdrawal INST NUM 13136822245",
            debit: "50,000.00",
            credit: "",
            balance: "13,79,628.07",
        },
        {
            date: "14-Aug-2024",
            valueDate: "14-Aug-2024",
            originatingBranch: "",
            transaction: "Repayment Of 1313648000699",
            debit: "23,000.00",
            credit: "",
            balance: "13,56,628.07",
        },
        {
            date: "01-Sep-2024",
            valueDate: "01-Sep-2024",
            originatingBranch: "",
            transaction: "Repayment Of 1313648000699",
            debit: "23,000.00",
            credit: "",
            balance: "13,33,828.07",
        },
        {
            date: "01-Sep-2024",
            valueDate: "01-Sep-2024",
            originatingBranch: "",
            transaction:
                "BEFTN Transfer 2024080153981324 TREASURY SINGLE ACCOUNT-3000183386 TREASURY SINGLE-BB: MOTIJHEEL L PAD",
            debit: "",
            credit: "48,064.83",
            balance: "13,81,692.90",
        },
        {
            date: "11-Sep-2024",
            valueDate: "11-Sep-2024",
            originatingBranch: "",
            transaction: "Cash Withdrawal INST NUM 13136822246",
            debit: "20,000.00",
            credit: "",
            balance: "13,61,692.90",
        },
        {
            date: "18-Sep-2024",
            valueDate: "18-Sep-2024",
            originatingBranch: "Parahuram Branch, Feni",
            transaction: "Cash Withdrawal INST NUM SB1313867379",
            debit: "10,000.00",
            credit: "",
            balance: "13,51,692.90",
        },
        {
            date: "24-Sep-2024",
            valueDate: "24-Sep-2024",
            originatingBranch: "",
            transaction: "Cash Withdrawal INST NUM 13136822247",
            debit: "1,00,000.00",
            credit: "",
            balance: "12,51,692.90",
        },
        {
            date: "02-Oct-2024",
            valueDate: "02-Oct-2024",
            originatingBranch: "",
            transaction: "Salary",
            debit: "",
            credit: "47,698.11",
            balance: "12,99,391.01",
        },
        {
            date: "02-Oct-2024",
            valueDate: "02-Oct-2024",
            originatingBranch: "",
            transaction: "Repayment Of 131364800059",
            debit: "22,810.00",
            credit: "",
            balance: "12,76,581.01",
        },
        {
            date: "23-Oct-2024",
            valueDate: "23-Oct-2024",
            originatingBranch: "",
            transaction: "Cash Withdrawal INST NUM 13136822250",
            debit: "10,000.00",
            credit: "",
            balance: "12,66,581.01",
        },
        {
            date: "23-Oct-2024",
            valueDate: "23-Oct-2024",
            originatingBranch: "",
            transaction: "Cheque Book Issue Charges",
            debit: "40.00",
            credit: "",
            balance: "12,66,541.01",
        },
        {
            date: "03-Nov-2024",
            valueDate: "03-Nov-2024",
            originatingBranch: "",
            transaction:
                "BEFTN Transfer 2024110314138829 TREASURY SINGLE ACCCOUN–2000183356 TREASURY SINGLE_BB: MOTLHEEL.PAD",
            debit: "",
            credit: "52,631.38",
            balance: "13,19,172.39",
        },
        {
            date: "04-Nov-2024",
            valueDate: "04-Nov-2024",
            originatingBranch: "",
            transaction: "Account Closure Of 131364800059",
            debit: "9,44,413.17",
            credit: "",
            balance: "3,74,759.22",
        },
        {
            date: "01-Dec-2024",
            valueDate: "01-Dec-2024",
            originatingBranch: "",
            transaction:
                "BEFTN Transfer 2024120155258567 TREASURY SINGLE ACCOUN–30001833585 TREASURY SINGLE_BB: MOTLHEEL PAD",
            debit: "",
            credit: "52,154.72",
            balance: "4,26,913.94",
        },
        {
            date: "19-Dec-2024",
            valueDate: "19-Dec-2024",
            originatingBranch: "Cumilla Cantonment Branch, Cumilla",
            transaction: "Statement Charge",
            debit: "100.00",
            credit: "",
            balance: "4,26,813.94",
        },
        {
            date: "19-Dec-2024",
            valueDate: "19-Dec-2024",
            originatingBranch: "Cumilla Cantonment Branch, Cumilla",
            transaction: "VAT On Statement Charge",
            debit: "15.00",
            credit: "",
            balance: "4,26,798.94",
        },
        {
            date: "19-Dec-2024",
            valueDate: "19-Dec-2024",
            originatingBranch: "HEAD OFFICE",
            transaction: "Ewallet A2A-NPSB To:4567900275058185",
            debit: "80,010.00",
            credit: "",
            balance: "3,46,788.94",
        },
        {
            date: "19-Dec-2024",
            valueDate: "19-Dec-2024",
            originatingBranch: "",
            transaction:
                "Deposits From AC:0002000000000 ,branch:,bank:ific Bank PLC",
            debit: "",
            credit: "3,00,000.00",
            balance: "6,46,788.94",
        },
        {
            date: "19-Dec-2024",
            valueDate: "19-Dec-2024",
            originatingBranch: "HEAD OFFICE",
            transaction: "Ewallet A2A-NPSB To:4059901019183",
            debit: "3,00,010.00",
            credit: "",
            balance: "3,46,778.94",
        },
        {
            date: "19-Dec-2024",
            valueDate: "19-Dec-2024",
            originatingBranch: "HEAD OFFICE",
            transaction: "Ewallet A2A-NPSB To:4059901019183",
            debit: "1,29,510.00",
            credit: "",
            balance: "2,17,268.94",
        },
        {
            date: "22-Dec-2024",
            valueDate: "22-Dec-2024",
            originatingBranch: "Local Office, Dhaka",
            transaction:
                "EFT AUTO 202412226407157 MD SHAKIL KHAN–02:10286759851–Other Bank Trans Fe-ific: MOHA",
            debit: "",
            credit: "1,29,500.00",
            balance: "3,46,768.94",
        },
        {
            date: "27-Dec-2024",
            valueDate: "27-Dec-2024",
            originatingBranch: "",
            transaction: "Maintenance Charge",
            debit: "300.00",
            credit: "",
            balance: "3,46,468.94",
        },
        {
            date: "27-Dec-2024",
            valueDate: "27-Dec-2024",
            originatingBranch: "",
            transaction: "VAT On Maintenance Charge For Product 1000",
            debit: "45.00",
            credit: "",
            balance: "3,46,423.94",
        },
        {
            date: "27-Dec-2024",
            valueDate: "27-Dec-2024",
            originatingBranch: "",
            transaction: "SMS Charger(Transactional Alert)",
            debit: "50.00",
            credit: "",
            balance: "3,46,373.94",
        },
        {
            date: "27-Dec-2024",
            valueDate: "27-Dec-2024",
            originatingBranch: "",
            transaction: "SMS Charge VAT(Transactional Alert)",
            debit: "8.00",
            credit: "",
            balance: "3,46,365.94",
        },
        {
            date: "27-Dec-2024",
            valueDate: "27-Dec-2024",
            originatingBranch: "",
            transaction: "SMS Charger(Push Pull)",
            debit: "50.00",
            credit: "",
            balance: "3,46,315.94",
        },
        {
            date: "27-Dec-2024",
            valueDate: "27-Dec-2024",
            originatingBranch: "",
            transaction: "SMS Charge VAT(Plush Pull)",
            debit: "8.00",
            credit: "",
            balance: "3,46,307.94",
        },
        {
            date: "31-Dec-2024",
            valueDate: "31-Dec-2024",
            originatingBranch: "",
            transaction: "Interest Applied",
            debit: "",
            credit: "10,863.00",
            balance: "3,57,170.94",
        },
        {
            date: "31-Dec-2024",
            valueDate: "31-Dec-2024",
            originatingBranch: "",
            transaction: "TDS Deduction On Interest Amount",
            debit: "1,630.00",
            credit: "",
            balance: "3,55,540.94",
        },
        {
            date: "31-Dec-2024",
            valueDate: "31-Dec-2024",
            originatingBranch: "",
            transaction: "Excise Duty 2024",
            debit: "3,000.00",
            credit: "",
            balance: "3,52,540.94",
        },
        {
            date: "01-Jan-2025",
            valueDate: "01-Jan-2025",
            originatingBranch: "Local Office, Dhaka",
            transaction:
                "EFT AUTO 2025010150481183 TREASURY SINGLE ACCOUN~30001833565~Monthly P Ens-bb: MOTIJH",
            debit: "",
            credit: "52,426.54",
            balance: "4,04,967.48",
        },
        {
            date: "20-Jan-2025",
            valueDate: "20-Jan-2025",
            originatingBranch: "",
            transaction: "Cash Withdrawal INST NUM 131367440314",
            debit: "3,00,100.00",
            credit: "",
            balance: "1,04,867.48",
        },
        {
            date: "21-Jan-2025",
            valueDate: "21-Jan-2025",
            originatingBranch: "",
            transaction: "Cash Withdrawal INST NUM 131367440313",
            debit: "1,00,000.00",
            credit: "",
            balance: "4,867.48",
        },
        {
            date: "28-Jan-2025",
            valueDate: "28-Jan-2025",
            originatingBranch: "",
            transaction:
                "RTGS - THE CITY BANK LTD. Transfe UTR : CBIA2501283451427 BIC : GIBLBDDH",
            debit: "",
            credit: "9,00,000.00",
            balance: "9,04,867.48",
        },
        {
            date: "02-Feb-2025",
            valueDate: "02-Feb-2025",
            originatingBranch: "Local Office, Dhaka",
            transaction:
                "EFT AUTO 20250228217417 TREASURY SINGLE ACCOUN~30001833565~Salary Pay Me-bb: MOTIJH",
            debit: "",
            credit: "52,502.57",
            balance: "9,57,370.05",
        },
        {
            date: "09-Feb-2025",
            valueDate: "09-Feb-2025",
            originatingBranch: "",
            transaction: "Malm Uddin INST NUM 131367440320",
            debit: "2,00,000.00",
            credit: "",
            balance: "7,57,370.05",
        },
        {
            date: "24-Feb-2025",
            valueDate: "24-Feb-2025",
            originatingBranch: "",
            transaction: "Cash Withdrawal INST NUM 131367440317",
            debit: "2,00,000.00",
            credit: "",
            balance: "5,57,370.05",
        },
        {
            date: "24-Feb-2025",
            valueDate: "24-Feb-2025",
            originatingBranch: "",
            transaction: "Cheque Book Issue Charges",
            debit: "25.00",
            credit: "",
            balance: "5,57,345.05",
        },
        {
            date: "02-Mar-2025",
            valueDate: "02-Mar-2025",
            originatingBranch: "",
            transaction:
                "BERTH Transfer 2025030212255656 TREASURY SINGLE ACCOUN~30001833565 TREASURY SINGLE-BB: MOTLIHEEL PAD",
            debit: "",
            credit: "46,715.00",
            balance: "6,04,060.05",
        },
        {
            date: "05-Mar-2025",
            valueDate: "05-Mar-2025",
            originatingBranch: "",
            transaction: "Cash Withdrawal INST NUM 131367440316",
            debit: "2,00,000.00",
            credit: "",
            balance: "4,04,060.05",
        },
        {
            date: "06-Mar-2025",
            valueDate: "06-Mar-2025",
            originatingBranch: "Local Office, Dhaka",
            transaction:
                "EFT AUTO 20250308703342 TREASURY SINGLE ACCOUN~30001833565~Payment Fr Om-bb: MOTIJH",
            debit: "",
            credit: "5,210.00",
            balance: "4,09,270.05",
        },
        {
            date: "06-Mar-2025",
            valueDate: "06-Mar-2025",
            originatingBranch: "Local Office, Dhaka",
            transaction:
                "EFT AUTO 20250308651573 TREASURY SINGLE ACCOUN~30001833565~Payment Fr Om-bb: MOTIJH",
            debit: "",
            credit: "26,090.00",
            balance: "4,35,360.05",
        },
        {
            date: "13-Mar-2025",
            valueDate: "13-Mar-2025",
            originatingBranch: "",
            transaction: "Cash Withdrawal INST NUM 131367440318",
            debit: "1,50,000.00",
            credit: "",
            balance: "2,85,360.05",
        },
        {
            date: "20-Mar-2025",
            valueDate: "20-Mar-2025",
            originatingBranch: "",
            transaction: "Cash Withdrawal INST NUM 131367440315",
            debit: "1,10,000.00",
            credit: "",
            balance: "1,75,360.05",
        },
        {
            date: "23-Mar-2025",
            valueDate: "23-Mar-2025",
            originatingBranch: "",
            transaction:
                "BERTH Transfer 2025032391234384 TREASURY SINGLE ACCOUN~30001833565 TREASURY SINGLE-BB: MOTLIHEEL PAD",
            debit: "",
            credit: "49,380.00",
            balance: "2,24,740.05",
        },
        {
            date: "25-Mar-2025",
            valueDate: "25-Mar-2025",
            originatingBranch: "",
            transaction: "Cash Withdrawal INST NUM 13136822248",
            debit: "1,22,000.00",
            credit: "",
            balance: "1,02,740.05",
        },
        {
            date: "30-Apr-2025",
            valueDate: "30-Apr-2025",
            originatingBranch: "Guthuma Bazar Branch, Feni",
            transaction: "BEFTN INST NUM 131367440311",
            debit: "21,000.00",
            credit: "",
            balance: "81,740.05",
        },
        {
            date: "04-May-2025",
            valueDate: "04-May-2025",
            originatingBranch: "Local Office, Dhaka",
            transaction:
                "EFT AUTO 2025060413204120 TREASURY SINGLE ACCOUN~30001833565~Salary Pa Yme-bb: MOTIJH",
            debit: "",
            credit: "52,677.26",
            balance: "1,34,417.31",
        },
        {
            date: "12-May-2025",
            valueDate: "12-May-2025",
            originatingBranch: "Local Office, Dhaka",
            transaction:
                "EFT AUTO 202506050338676 TREASURY SINGLE ACCOUN~30001833565~Payment F Rom-bb: MOTIJH",
            debit: "",
            credit: "26,090.00",
            balance: "1,60,507.31",
        },
        {
            date: "20-May-2025",
            valueDate: "20-May-2025",
            originatingBranch: "Guthuma Bazar Branch, Feni",
            transaction: "TR- BEFTN INST NUM 131368492294",
            debit: "20,000.00",
            credit: "",
            balance: "1,40,507.31",
        },
        {
            date: "21-May-2025",
            valueDate: "21-May-2025",
            originatingBranch: "",
            transaction: "Cash Withdrawal INST NUM 131368492291",
            debit: "1,00,000.00",
            credit: "",
            balance: "40,507.31",
        },
        {
            date: "01-Jun-2025",
            valueDate: "01-Jun-2025",
            originatingBranch: "",
            transaction:
                "BEFTN Transfer 2025060122914347 TREASURY SINGLE ACCOUN~30001833565 TREASURY SINGLE-BB: MOTLHEEL PAD",
            debit: "",
            credit: "52,638.19",
            balance: "93,145.50",
        },
        {
            date: "02-Jun-2025",
            valueDate: "02-Jun-2025",
            originatingBranch: "",
            transaction: "Cash Withdrawal INST NUM 131368492300",
            debit: "92,000.00",
            credit: "",
            balance: "1,145.50",
        },
        {
            date: "02-Jun-2025",
            valueDate: "02-Jun-2025",
            originatingBranch: "",
            transaction: "Cheque Book Issue Charges",
            debit: "120.00",
            credit: "",
            balance: "1,025.50",
        },
    ];

    return (
        <div style={{ height: "100vh" }}>
            <PDFViewer width="100%" height="100%">
                <StatementPDF data={transactions} />
            </PDFViewer>
        </div>
    );
};

export default PdfViewerPage;
