// components/StatementPDF.jsx
import React from "react";
import {
    Document,
    Page,
    Text,
    View,
    StyleSheet,
    Font,
    Image,
} from "@react-pdf/renderer";
import { Table, TR, TH, TD } from "@ag-media/react-pdf-table";

// Styles
const styles = StyleSheet.create({
    page: {
        paddingHorizontal: 40,
        paddingVertical: 70,
        fontSize: 7,
        fontFamily: "Helvetica",
    },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 10,
        width: "100%",
    },
    section: {
        // marginBottom: 5,
        fontSize: 7,
        borderWidth: 1,
    },
    by: {
        fontSize: 5,
        color: "gray",
    },
    bold: {
        fontWeight: "bold",
    },
    center: {
        textAlign: "center",
        fontWeight: "bold",
        marginVertical: 4,
        fontSize: 9,
        marginTop: 10,
    },
    tableHeader: {
        flexDirection: "row",
        borderBottomWidth: 1,
        borderTopWidth: 1,
        borderLeftWidth: 1,
        borderRightWidth: 1,
    },
    row: {
        flexDirection: "row",
        borderBottomWidth: 1,
        borderLeftWidth: 1,
        borderRightWidth: 1,
    },
    cell: {
        paddingHorizontal: 2,
        borderRightWidth: 1,
        paddingVertical: 2,
    },
    lastCell: {
        paddingHorizontal: 2,
        borderRightWidth: 0, // No border for the last cell in row
        paddingVertical: 2,
    },
    footer: {
        position: "absolute",
        bottom: 70,
        right: 70,
        flexDirection: "row",
        justifyContent: "flex-end",
    },
    columnWidths: {
        date: "12%",
        valueDate: "12%",
        branch: "23%",
        transaction: "25%",
        debit: "14%",
        credit: "14%",
        balance: "16%",
    },
    image: {
        width: 90,
        height: 25,
    },
});

const PageWrapper = ({ children }) => {
    const branchName = "DAULATGONJ CUMILLA";
    const branchAddress = "13136 - DAULATGONJ CUMILLA CUMILLA";
    const userInfo = {
        name: "MD KABIR KHAN",
        address: ["VILL- RAMPUR,", "POST-UTTARDA,", "LAKSAM,", "COMILLA"],
        openingDate: "07-Aug-2018",
        accountNumber: "13124551542415",
        interest: "2.5",
        accountType: "SB - Savings Bank Account (General)",
        period: "01-Jul-2024 - 31-Dec-2024",
        status: "Active",
        routing: "200191548",
    };

    return (
        <>
            <Table style={{ border: "0px" }}>
                <TH style={{ fontWeight: "normal" }}>
                    <Table style={{ border: "0px" }}>
                        <TR>
                            <TD style={{ width: "100%" }}>
                                <View style={styles.header}>
                                    <View>
                                        <Image
                                            style={styles.image}
                                            src="./sonali.jpg"
                                        />
                                        <Text style={styles.by}>
                                            Generated By
                                        </Text>
                                        <Text>{branchName}</Text>
                                        <Text>{branchAddress}</Text>
                                    </View>
                                    <View style={{ gap: 6 }}>
                                        <Text>
                                            <Text style={styles.bold}>
                                                Print Date:{" "}
                                            </Text>{" "}
                                            01-Jul-2024
                                        </Text>
                                        <Text>
                                            <Text style={styles.bold}>
                                                Print Time:{" "}
                                            </Text>
                                            11:09 AM
                                        </Text>
                                        <Text>
                                            <Text style={styles.bold}>
                                                User ID:{" "}
                                            </Text>
                                            {"     "}46238
                                        </Text>
                                    </View>
                                </View>
                            </TD>
                        </TR>
                        <TR>
                            <TD
                                style={{
                                    width: "100%",
                                    justifyContent: "center",
                                }}
                            >
                                <Text style={styles.center}>
                                    STATEMENT OF ACCOUNT
                                </Text>
                            </TD>
                        </TR>
                        <TR>
                            <TD>
                                <Table>
                                    <TR>
                                        <TD
                                            style={{
                                                alignItems: "flex-start",
                                                paddingVertical: 4,
                                            }}
                                        >
                                            <View
                                                style={{
                                                    paddingHorizontal: 8,
                                                }}
                                            >
                                                <Text
                                                    style={[
                                                        styles.bold,
                                                        {
                                                            marginBottom: 12,
                                                        },
                                                    ]}
                                                >
                                                    {userInfo.name}
                                                </Text>
                                                {userInfo.address.map(
                                                    (line, idx) => (
                                                        <Text
                                                            key={idx}
                                                            style={{
                                                                marginBottom: 3,
                                                            }}
                                                        >
                                                            {line}
                                                        </Text>
                                                    )
                                                )}
                                            </View>
                                        </TD>
                                        <TD>
                                            <View
                                                style={{
                                                    paddingHorizontal: 4,
                                                }}
                                            >
                                                <Text>
                                                    <Text style={styles.bold}>
                                                        Branch :{" "}
                                                    </Text>
                                                    {branchAddress}
                                                </Text>
                                                <Text>
                                                    <Text style={styles.bold}>
                                                        Currency :{" "}
                                                    </Text>
                                                    BDT
                                                </Text>
                                                <Text>
                                                    <Text style={styles.bold}>
                                                        Opening Date :{" "}
                                                    </Text>
                                                    {userInfo.openingDate}
                                                </Text>
                                                <Text>
                                                    <Text style={styles.bold}>
                                                        Account Number :{" "}
                                                    </Text>
                                                    {userInfo.accountNumber}
                                                </Text>
                                                <Text>
                                                    <Text style={styles.bold}>
                                                        Interest Rate :{" "}
                                                    </Text>
                                                    {userInfo.interest}
                                                </Text>
                                                <Text style={styles.bold}>
                                                    Account Type :{" "}
                                                    {userInfo.accountType}
                                                </Text>
                                                <Text>
                                                    <Text style={styles.bold}>
                                                        Period :{" "}
                                                    </Text>
                                                    {userInfo.period}
                                                </Text>
                                                <Text>
                                                    <Text style={styles.bold}>
                                                        Status :{" "}
                                                    </Text>
                                                    {userInfo.status}
                                                </Text>
                                                <Text>
                                                    <Text style={styles.bold}>
                                                        Routing Number :{" "}
                                                    </Text>
                                                    {userInfo.routing}
                                                </Text>
                                            </View>
                                        </TD>
                                    </TR>
                                </Table>
                            </TD>
                        </TR>

                        <TR
                            style={{
                                marginTop: 20,
                            }}
                        >
                            <TD>
                                <Table
                                    weightings={[
                                        1.25, 1.25, 2.5, 3.5, 1.45, 1.45, 2,
                                    ]}
                                >
                                    <TH>
                                        <TD
                                            style={{
                                                justifyContent: "center",
                                                paddingHorizontal: 1,
                                                paddingVertical: 3,
                                            }}
                                        >
                                            Date
                                        </TD>
                                        <TD
                                            style={{
                                                justifyContent: "center",
                                                paddingHorizontal: 1,
                                                paddingVertical: 3,
                                            }}
                                        >
                                            Value Date
                                        </TD>
                                        <TD
                                            style={{
                                                paddingHorizontal: 1,
                                                paddingVertical: 3,
                                            }}
                                        >
                                            Originating Branch
                                        </TD>
                                        <TD
                                            style={{
                                                paddingHorizontal: 1,
                                                paddingVertical: 3,
                                            }}
                                        >
                                            Transaction
                                        </TD>
                                        <TD
                                            style={{
                                                justifyContent: "flex-end",
                                                paddingHorizontal: 1,
                                                paddingVertical: 3,
                                            }}
                                        >
                                            Debit
                                        </TD>
                                        <TD
                                            style={{
                                                justifyContent: "flex-end",
                                                paddingHorizontal: 1,
                                                paddingVertical: 3,
                                            }}
                                        >
                                            Credit
                                        </TD>
                                        <TD
                                            style={{
                                                justifyContent: "flex-end",
                                                paddingHorizontal: 1,
                                                paddingVertical: 3,
                                                paddingLeft: 3,
                                            }}
                                        >
                                            Balance
                                        </TD>
                                    </TH>
                                    <TR>
                                        <TD
                                            style={{
                                                justifyContent: "center",
                                                paddingHorizontal: 1,
                                                paddingVertical: 4,
                                                borderBottom: 0,
                                            }}
                                        ></TD>
                                        <TD
                                            style={{
                                                justifyContent: "center",
                                                paddingHorizontal: 1,
                                                paddingVertical: 4,
                                                borderBottom: 0,
                                            }}
                                        ></TD>
                                        <TD
                                            style={{
                                                paddingHorizontal: 1,
                                                paddingVertical: 4,
                                                borderBottom: 0,
                                            }}
                                        ></TD>
                                        <TD
                                            style={{
                                                paddingHorizontal: 1,
                                                paddingTop: 3,
                                                paddingBottom: 6,
                                                fontWeight: "bold",
                                                borderBottom: 0,
                                            }}
                                        >
                                            Opening Balance
                                        </TD>
                                        <TD
                                            style={{
                                                justifyContent: "flex-end",
                                                paddingHorizontal: 1,
                                                paddingVertical: 4,
                                                borderBottom: 0,
                                            }}
                                        ></TD>
                                        <TD
                                            style={{
                                                justifyContent: "flex-end",
                                                paddingHorizontal: 1,
                                                paddingVertical: 4,
                                                borderBottom: 0,
                                            }}
                                        ></TD>
                                        <TD
                                            style={{
                                                justifyContent: "flex-end",
                                                alignItems: "flex-start",
                                                paddingHorizontal: 1,
                                                paddingRight: 3,
                                                paddingVertical: 3,
                                                borderBottom: 0,
                                            }}
                                        >
                                            <View
                                                style={{
                                                    flexDirection: "row",
                                                    alignItems: "center",
                                                }}
                                            >
                                                <Text style={styles.bold}>
                                                    65000.00
                                                </Text>
                                                <Text style={{ fontSize: 5 }}>
                                                    {" "}
                                                    CR
                                                </Text>
                                            </View>
                                        </TD>
                                    </TR>
                                </Table>
                            </TD>
                        </TR>
                    </Table>
                </TH>
            </Table>

            {/* CHILD TABLE ROWS */}
            {children}
        </>
    );
};

const StatementPDF = ({ data = [] }) => {
    const branchName = "DAULATGONJ CUMILLA";
    const branchAddress = "13136 - DAULATGONJ CUMILLA CUMILLA";
    const userInfo = {
        name: "MD KABIR KHAN",
        address: ["VILL- RAMPUR,", "POST-UTTARDA,", "LAKSAM,", "COMILLA"],
        openingDate: "07-Aug-2018",
        accountNumber: "13124551542415",
        interest: "2.5",
        accountType: "SB - Savings Bank Account (General)",
        period: "01-Jul-2024 - 31-Dec-2024",
        status: "Active",
        routing: "200191548",
    };

    const totalDebit = data.reduce(
        (sum, d) => sum + parseFloat(d.debit || 0),
        0
    );
    const totalCredit = data.reduce(
        (sum, d) => sum + parseFloat(d.credit || 0),
        0
    );

    const pageSize = 22;
    const totalPages = Math.ceil(data.length / pageSize);
    console.log("🚀 ~ totalPages:", totalPages);

    return (
        <Document>
            {Array.from({ length: totalPages }).map((_, pageIndex) => {
                const start = pageIndex * pageSize;
                const end = start + pageSize;
                const pageData = data.slice(start, end);

                return (
                    <Page key={pageIndex} size="A4" style={styles.page}>
                        <PageWrapper>
                            <Table>
                                <TR>
                                    <TD>
                                        <Table
                                            weightings={[
                                                1.25, 1.25, 2.5, 3.5, 1.45,
                                                1.45, 2,
                                            ]}
                                        >
                                            {pageData.map((item, index) => (
                                                <TR key={index}>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "center",
                                                            alignItems:
                                                                "flex-start",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 4,
                                                        }}
                                                    >
                                                        {item.date}
                                                    </TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "center",
                                                            alignItems:
                                                                "flex-start",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 4,
                                                        }}
                                                    >
                                                        {item.valueDate}
                                                    </TD>
                                                    <TD
                                                        style={{
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 4,
                                                        }}
                                                    >
                                                        {item.originatingBranch}
                                                    </TD>
                                                    <TD
                                                        style={{
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 0,
                                                        }}
                                                    >
                                                        {item.transaction}
                                                    </TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "flex-start",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 4,
                                                        }}
                                                    >
                                                        {item.debit
                                                            ? Number(
                                                                  item.debit
                                                              ).toFixed(2)
                                                            : ""}
                                                    </TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "flex-start",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 4,
                                                        }}
                                                    >
                                                        {item.credit
                                                            ? Number(
                                                                  item.credit
                                                              ).toFixed(2)
                                                            : ""}
                                                    </TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "flex-start",
                                                            paddingHorizontal: 1,
                                                            paddingRight: 3,
                                                            paddingVertical: 4,
                                                        }}
                                                    >
                                                        <View
                                                            style={{
                                                                flexDirection:
                                                                    "row",
                                                                alignItems:
                                                                    "center",
                                                            }}
                                                        >
                                                            <Text>
                                                                {Number(
                                                                    item.balance
                                                                ).toFixed(2)}
                                                            </Text>
                                                            <Text
                                                                style={{
                                                                    fontSize: 5,
                                                                }}
                                                            >
                                                                {" "}
                                                                CR
                                                            </Text>
                                                        </View>
                                                    </TD>
                                                </TR>
                                            ))}
                                        </Table>
                                    </TD>
                                </TR>
                            </Table>
                            {pageIndex + 1 === totalPages ? (
                                <Table>
                                    <TH>
                                        <TD style={{ borderTop: 0 }}>
                                            <Table
                                                style={{ border: "0px" }}
                                                weightings={[
                                                    1.25, 1.25, 2.5, 3.5, 1.45,
                                                    1.45, 2,
                                                ]}
                                            >
                                                <TH>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 6,
                                                        }}
                                                    >
                                                        Grand Total
                                                    </TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 6,
                                                        }}
                                                    >
                                                        56264.00
                                                    </TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 6,
                                                        }}
                                                    >
                                                        563157.00
                                                    </TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                            paddingLeft: 3,
                                                        }}
                                                    ></TD>
                                                </TH>
                                            </Table>
                                        </TD>
                                    </TH>
                                    <TH>
                                        <TD style={{ borderTop: 0 }}>
                                            <Table
                                                style={{ border: "0px" }}
                                                weightings={[
                                                    1.25, 1.25, 2.5, 3.5, 1.45,
                                                    1.45, 2,
                                                ]}
                                            >
                                                <TH>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "center",
                                                            alignItems:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 6,
                                                        }}
                                                    >
                                                        Closing Balance
                                                    </TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 6,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 6,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingRight: 3,
                                                            paddingVertical: 4,
                                                        }}
                                                    >
                                                        <View
                                                            style={{
                                                                flexDirection:
                                                                    "row",
                                                                alignItems:
                                                                    "center",
                                                            }}
                                                        >
                                                            <Text
                                                                style={
                                                                    styles.bold
                                                                }
                                                            >
                                                                {Number(
                                                                    5642.05
                                                                ).toFixed(2)}
                                                            </Text>
                                                            <Text
                                                                style={{
                                                                    fontSize: 5,
                                                                }}
                                                            >
                                                                {" "}
                                                                CR
                                                            </Text>
                                                        </View>
                                                    </TD>
                                                </TH>
                                            </Table>
                                        </TD>
                                    </TH>
                                    <TH>
                                        <TD
                                            style={{
                                                borderTop: 0,
                                                borderLeft: 0,
                                                borderRight: 0,
                                            }}
                                        >
                                            <Table
                                                style={{ border: "0px" }}
                                                weightings={[
                                                    1.25, 1.25, 2.5, 3.5, 1.45,
                                                    1.45, 2,
                                                ]}
                                            >
                                                <TH>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                            paddingLeft: 62,
                                                            paddingBottom: 25,
                                                        }}
                                                    >
                                                        Balance C/F
                                                    </TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingRight: 3,
                                                            paddingVertical: 4,
                                                            paddingBottom: 25,
                                                        }}
                                                    >
                                                        <View
                                                            style={{
                                                                flexDirection:
                                                                    "row",
                                                                alignItems:
                                                                    "center",
                                                            }}
                                                        >
                                                            <Text
                                                                style={
                                                                    styles.bold
                                                                }
                                                            >
                                                                {Number(
                                                                    5642.05
                                                                ).toFixed(2)}
                                                            </Text>
                                                            <Text
                                                                style={{
                                                                    fontSize: 5,
                                                                }}
                                                            >
                                                                {" "}
                                                                CR
                                                            </Text>
                                                        </View>
                                                    </TD>
                                                </TH>
                                            </Table>
                                        </TD>
                                    </TH>
                                    <TH>
                                        <TD
                                            style={{
                                                borderTop: 0,
                                                borderBottom: 0,
                                                borderLeft: 0,
                                                borderRight: 0,
                                                paddingTop: 8,
                                                justifyContent: "center",
                                            }}
                                        >
                                            <Text>
                                                ******* End of Report *******
                                            </Text>
                                        </TD>
                                    </TH>
                                </Table>
                            ) : (
                                <Table
                                    style={{ border: "0px" }}
                                    weightings={[
                                        1.25, 1.25, 2.5, 3.5, 1.45, 1.45, 2,
                                    ]}
                                >
                                    <TH>
                                        <TD
                                            style={{
                                                justifyContent: "center",
                                                paddingHorizontal: 1,
                                            }}
                                        ></TD>
                                        <TD
                                            style={{
                                                justifyContent: "center",
                                                paddingHorizontal: 1,
                                            }}
                                        ></TD>
                                        <TD
                                            style={{
                                                paddingHorizontal: 1,
                                            }}
                                        ></TD>
                                        <TD
                                            style={{
                                                justifyContent: "flex-end",
                                                paddingHorizontal: 2,
                                                paddingVertical: 1,
                                            }}
                                        >
                                            Total
                                        </TD>
                                        <TD
                                            style={{
                                                justifyContent: "flex-end",
                                                paddingHorizontal: 2,
                                                paddingVertical: 1,
                                            }}
                                        >
                                            564.00
                                        </TD>
                                        <TD
                                            style={{
                                                justifyContent: "flex-end",
                                                paddingHorizontal: 2,
                                                paddingVertical: 1,
                                            }}
                                        >
                                            8654.00
                                        </TD>
                                        <TD
                                            style={{
                                                justifyContent: "flex-end",
                                                paddingHorizontal: 1,
                                                paddingLeft: 3,
                                            }}
                                        ></TD>
                                    </TH>
                                </Table>
                            )}

                            {/* Footer - Page Totals */}
                            <View style={styles.footer}>
                                <Text>
                                    Page {pageIndex + 1} of {totalPages}
                                </Text>
                            </View>
                        </PageWrapper>
                    </Page>
                );
            })}
        </Document>
    );
};

export default StatementPDF;
