// components/StatementPDF.jsx
import React from "react";
import {
    Document,
    Page,
    Text,
    View,
    StyleSheet,
    Font,
    Image,
} from "@react-pdf/renderer";
import { Table, TR, TH, TD } from "@ag-media/react-pdf-table";

// Styles
const styles = StyleSheet.create({
    page: {
        paddingHorizontal: 26,
        paddingVertical: 50,
        fontSize: 7,
        fontFamily: "Helvetica",
        // fontWeight: 100,
        lineHeight: 1.2,
    },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 10,
        width: "100%",
    },
    by: {
        fontSize: 6,
        color: "gray",
    },
    bold: {
        fontWeight: "bold",
    },
    center: {
        textAlign: "center",
        fontWeight: "bold",
        marginVertical: 7,
        fontSize: 10.5,
        marginTop: 8,
    },
    row: {
        flexDirection: "row",
        borderBottomWidth: 1,
        borderLeftWidth: 1,
        borderRightWidth: 1,
    },
    cell: {
        paddingHorizontal: 2,
        borderRightWidth: 1,
        paddingVertical: 2,
    },
    lastCell: {
        paddingHorizontal: 2,
        borderRightWidth: 0, // No border for the last cell in row
        paddingVertical: 2,
    },
    footer: {
        position: "absolute",
        bottom: 60,
        right: 70,
        flexDirection: "row",
        justifyContent: "flex-end",
    },
    columnWidths: {
        date: "12%",
        valueDate: "12%",
        branch: "23%",
        transaction: "25%",
        debit: "14%",
        credit: "14%",
        balance: "16%",
    },
    image: {
        width: 95,
        height: 32,
    },
});

const PageWrapper = ({ children }) => {
    const branchName = "Daulatgonj Branch, Cumilla";
    const branchAddress = "13136 - Daulatgonj Branch, Cumilla .";
    const userInfo = {
        name: "MD KABIR KHAN",
        address: ["VILL- RAMPUR,", "POST-UTTARDA,", "LAKSAM,", "COMILLA"],
        openingDate: "07-Aug-2018",
        accountNumber: "1313601016892",
        interest: "2.75",
        accountType: "SB - Savings Bank Account (General)",
        period: "01-Jun-2024 - 14-Jun-2025",
        status: "Active",
        routing: "200191548",
    };

    return (
        <>
            <Table style={{ border: "0px" }}>
                <TH style={{ fontWeight: "normal" }}>
                    <Table style={{ border: "0px" }}>
                        <TR>
                            <TD style={{ width: "100%" }}>
                                <View style={styles.header}>
                                    <View>
                                        <Image
                                            style={styles.image}
                                            src="./sonali.jpg"
                                        />
                                        <Text style={styles.by}>
                                            Generated By
                                        </Text>
                                        <Text>{branchName}</Text>
                                        <Text>{branchAddress}</Text>
                                    </View>
                                    <View style={{ gap: 6 }}>
                                        <Text>
                                            <Text style={styles.bold}>
                                                Print Date{" "}
                                            </Text>{" "}
                                            15-Jun-2025
                                        </Text>
                                        <Text>
                                            <Text style={styles.bold}>
                                                Print Time{"  "}
                                            </Text>
                                            1:36 PM
                                        </Text>
                                        <Text>
                                            <Text style={styles.bold}>
                                                User ID:{" "}
                                            </Text>
                                            {"     "}46238
                                        </Text>
                                    </View>
                                </View>
                            </TD>
                        </TR>
                        <TR>
                            <TD
                                style={{
                                    width: "100%",
                                    justifyContent: "center",
                                }}
                            >
                                <Text style={styles.center}>
                                    STATEMENT OF ACCOUNT
                                </Text>
                            </TD>
                        </TR>
                        <TR>
                            <TD>
                                <Table>
                                    <TR>
                                        <TD
                                            style={{
                                                alignItems: "flex-start",
                                                paddingVertical: 4,
                                            }}
                                        >
                                            <View
                                                style={{
                                                    paddingHorizontal: 8,
                                                }}
                                            >
                                                <Text
                                                    style={[
                                                        styles.bold,
                                                        {
                                                            marginBottom: 12,
                                                        },
                                                    ]}
                                                >
                                                    {userInfo.name}
                                                </Text>
                                                {userInfo.address.map(
                                                    (line, idx) => (
                                                        <Text
                                                            key={idx}
                                                            style={{
                                                                marginBottom: 3,
                                                            }}
                                                        >
                                                            {line}
                                                        </Text>
                                                    )
                                                )}
                                            </View>
                                        </TD>
                                        <TD>
                                            <View
                                                style={{
                                                    paddingHorizontal: 4,
                                                }}
                                            >
                                                <Text>
                                                    <Text style={styles.bold}>
                                                        Branch :{" "}
                                                    </Text>
                                                    {branchAddress}
                                                </Text>
                                                <Text>
                                                    <Text style={styles.bold}>
                                                        Currency :{" "}
                                                    </Text>
                                                    BDT
                                                </Text>
                                                <Text>
                                                    <Text style={styles.bold}>
                                                        Opening Date :{" "}
                                                    </Text>
                                                    {userInfo.openingDate}
                                                </Text>
                                                <Text>
                                                    <Text style={styles.bold}>
                                                        Account Number :{" "}
                                                    </Text>
                                                    {userInfo.accountNumber}
                                                </Text>
                                                <Text>
                                                    <Text style={styles.bold}>
                                                        Interest Rate :{" "}
                                                    </Text>
                                                    {userInfo.interest}
                                                </Text>
                                                <Text style={styles.bold}>
                                                    Account Type :{" "}
                                                    {userInfo.accountType}
                                                </Text>
                                                <Text>
                                                    <Text style={styles.bold}>
                                                        Period :{" "}
                                                    </Text>
                                                    {userInfo.period}
                                                </Text>
                                                <Text>
                                                    <Text style={styles.bold}>
                                                        Status :{" "}
                                                    </Text>
                                                    {userInfo.status}
                                                </Text>
                                                <Text>
                                                    <Text style={styles.bold}>
                                                        Routing Number :{" "}
                                                    </Text>
                                                    {userInfo.routing}
                                                </Text>
                                            </View>
                                        </TD>
                                    </TR>
                                </Table>
                            </TD>
                        </TR>

                        <TR
                            style={{
                                marginTop: 20,
                            }}
                        >
                            <TD>
                                <Table
                                    weightings={[
                                        1.25, 1.25, 3.5, 3.5, 1.45, 1.45, 2,
                                    ]}
                                >
                                    <TH>
                                        <TD
                                            style={{
                                                justifyContent: "center",
                                                paddingHorizontal: 1,
                                                paddingVertical: 3,
                                            }}
                                        >
                                            Date
                                        </TD>
                                        <TD
                                            style={{
                                                justifyContent: "center",
                                                paddingHorizontal: 1,
                                                paddingVertical: 3,
                                            }}
                                        >
                                            Value Date
                                        </TD>
                                        <TD
                                            style={{
                                                paddingHorizontal: 2,
                                                paddingVertical: 3,
                                            }}
                                        >
                                            Originating Branch
                                        </TD>
                                        <TD
                                            style={{
                                                paddingHorizontal: 2,
                                                paddingVertical: 3,
                                            }}
                                        >
                                            Transaction
                                        </TD>
                                        <TD
                                            style={{
                                                justifyContent: "flex-end",
                                                paddingHorizontal: 1,
                                                paddingVertical: 3,
                                            }}
                                        >
                                            Debit
                                        </TD>
                                        <TD
                                            style={{
                                                justifyContent: "flex-end",
                                                paddingHorizontal: 1,
                                                paddingVertical: 3,
                                            }}
                                        >
                                            Credit
                                        </TD>
                                        <TD
                                            style={{
                                                justifyContent: "flex-end",
                                                paddingHorizontal: 1,
                                                paddingVertical: 3,
                                                paddingLeft: 6,
                                            }}
                                        >
                                            Balance
                                        </TD>
                                    </TH>
                                </Table>
                            </TD>
                        </TR>
                    </Table>
                </TH>
            </Table>

            {/* CHILD TABLE ROWS */}
            {children}
        </>
    );
};

const StatementPDF = ({ data = [] }) => {
    const pageSize = 22;
    const totalPages = Math.ceil(data.length / pageSize);

    return (
        <Document>
            {Array.from({ length: totalPages }).map((_, pageIndex) => {
                const start = pageIndex * (pageIndex === 3 ? 21 : pageSize);
                const end = start + (pageIndex === 2 ? 19 : pageSize);
                const pageData = data.slice(start, end);
                const cumulativeData = data.slice(0, end);
                const totalDebit = cumulativeData.reduce(
                    (sum, row) =>
                        sum + Number(row.debit.replace(/,/g, "") || 0),
                    0
                );
                const totalCredit = cumulativeData.reduce(
                    (sum, row) =>
                        sum + Number(row.credit.replace(/,/g, "") || 0),
                    0
                );
                const lastTransaction = pageData[pageData.length - 1];

                const balanceBF = data[start - 1]?.balance;
                console.log("🚀 ~ {Array.from ~ balanceBF:", balanceBF);

                return (
                    <Page key={pageIndex} size="LETTER" style={styles.page}>
                        <PageWrapper>
                            <Table>
                                <TR>
                                    <TD style={{ borderTop: 0 }}>
                                        <Table
                                            weightings={[
                                                1.25, 1.25, 3.5, 3.5, 1.45,
                                                1.45, 2,
                                            ]}
                                        >
                                            <TR>
                                                <TD
                                                    style={{
                                                        justifyContent:
                                                            "center",
                                                        paddingHorizontal: 1,
                                                        paddingVertical: 4,
                                                        borderTop: 0,
                                                    }}
                                                ></TD>
                                                <TD
                                                    style={{
                                                        justifyContent:
                                                            "center",
                                                        paddingHorizontal: 1,
                                                        paddingVertical: 4,
                                                        borderTop: 0,
                                                    }}
                                                ></TD>
                                                <TD
                                                    style={{
                                                        paddingHorizontal: 2,
                                                        paddingVertical: 4,
                                                        borderTop: 0,
                                                    }}
                                                ></TD>
                                                <TD
                                                    style={{
                                                        paddingLeft: 1,
                                                        paddingRight: 3,
                                                        marginTop: 5,
                                                        paddingBottom: 3,
                                                        fontWeight: "bold",
                                                        borderTop: 0,
                                                    }}
                                                >
                                                    {pageIndex === 0
                                                        ? "Opening Balance"
                                                        : "Balance B/F"}{" "}
                                                </TD>
                                                <TD
                                                    style={{
                                                        justifyContent:
                                                            "flex-end",
                                                        paddingHorizontal: 1,
                                                        paddingVertical: 4,
                                                        borderTop: 0,
                                                    }}
                                                ></TD>
                                                <TD
                                                    style={{
                                                        justifyContent:
                                                            "flex-end",
                                                        paddingHorizontal: 1,
                                                        paddingVertical: 4,
                                                        borderTop: 0,
                                                    }}
                                                ></TD>
                                                <TD
                                                    style={{
                                                        justifyContent:
                                                            "flex-end",
                                                        alignItems:
                                                            "flex-start",
                                                        paddingHorizontal: 1,
                                                        paddingRight: 6,
                                                        paddingVertical: 3,
                                                        borderTop: 0,
                                                        marginTop: 2,
                                                        paddingBottom: 3,
                                                    }}
                                                >
                                                    <View
                                                        style={{
                                                            flexDirection:
                                                                "row",
                                                            alignItems:
                                                                "center", // Changed from baseline to center
                                                            justifyContent:
                                                                "center",
                                                        }}
                                                    >
                                                        <Text
                                                            style={styles.bold}
                                                        >
                                                            {pageIndex === 0
                                                                ? "16,27,889.56"
                                                                : balanceBF}{" "}
                                                        </Text>
                                                        <View
                                                            style={{
                                                                justifyContent:
                                                                    "center",
                                                                alignItems:
                                                                    "center",
                                                            }}
                                                        >
                                                            <Text
                                                                style={{
                                                                    fontSize: 4.5, // Increased from 4
                                                                    lineHeight: 0, // Match font size
                                                                }}
                                                            >
                                                                CR
                                                            </Text>
                                                        </View>
                                                    </View>
                                                </TD>
                                            </TR>
                                        </Table>
                                    </TD>
                                </TR>
                                <TR>
                                    <TD>
                                        <Table
                                            weightings={[
                                                1.25, 1.25, 3.5, 3.5, 1.45,
                                                1.45, 2,
                                            ]}
                                        >
                                            {pageData.map((item, index) => {
                                                const debit = item.debit
                                                    ? Number(
                                                          item.debit.replace(
                                                              /,/g,
                                                              ""
                                                          )
                                                      ).toLocaleString(
                                                          "en-IN",
                                                          {
                                                              minimumFractionDigits: 2,
                                                              maximumFractionDigits: 2,
                                                          }
                                                      )
                                                    : "";
                                                const credit = item.credit
                                                    ? Number(
                                                          item.credit.replace(
                                                              /,/g,
                                                              ""
                                                          )
                                                      ).toLocaleString(
                                                          "en-IN",
                                                          {
                                                              minimumFractionDigits: 2,
                                                              maximumFractionDigits: 2,
                                                          }
                                                      )
                                                    : "";
                                                const balance = item.balance
                                                    ? Number(
                                                          item.balance.replace(
                                                              /,/g,
                                                              ""
                                                          )
                                                      ).toLocaleString(
                                                          "en-IN",
                                                          {
                                                              minimumFractionDigits: 2,
                                                              maximumFractionDigits: 2,
                                                          }
                                                      )
                                                    : "";
                                                return (
                                                    <TR key={index}>
                                                        <TD
                                                            style={{
                                                                justifyContent:
                                                                    "center",
                                                                alignItems:
                                                                    "flex-start",
                                                                paddingHorizontal: 1,
                                                                paddingVertical: 4,
                                                            }}
                                                        >
                                                            {item.date}
                                                        </TD>
                                                        <TD
                                                            style={{
                                                                justifyContent:
                                                                    "center",
                                                                alignItems:
                                                                    "flex-start",
                                                                paddingHorizontal: 1,
                                                                paddingVertical: 4,
                                                            }}
                                                        >
                                                            {item.valueDate}
                                                        </TD>
                                                        <TD
                                                            style={{
                                                                paddingHorizontal: 2,
                                                                paddingVertical: 4,
                                                            }}
                                                        >
                                                            {
                                                                item.originatingBranch
                                                            }
                                                        </TD>
                                                        <TD
                                                            style={{
                                                                paddingHorizontal: 2,
                                                                paddingVertical: 0,
                                                            }}
                                                        >
                                                            {item.transaction}
                                                        </TD>
                                                        <TD
                                                            style={{
                                                                justifyContent:
                                                                    "flex-end",
                                                                alignItems:
                                                                    "flex-start",
                                                                paddingHorizontal: 1,
                                                                paddingVertical: 4,
                                                            }}
                                                        >
                                                            {debit}
                                                        </TD>
                                                        <TD
                                                            style={{
                                                                justifyContent:
                                                                    "flex-end",
                                                                alignItems:
                                                                    "flex-start",
                                                                paddingHorizontal: 1,
                                                                paddingVertical: 4,
                                                            }}
                                                        >
                                                            {credit}
                                                        </TD>
                                                        <TD
                                                            style={{
                                                                justifyContent:
                                                                    "flex-end",
                                                                alignItems:
                                                                    "flex-start",
                                                                paddingHorizontal: 1,
                                                                paddingRight: 6,
                                                                paddingVertical: 4,
                                                            }}
                                                        >
                                                            <View
                                                                style={{
                                                                    flexDirection:
                                                                        "row",
                                                                    alignItems:
                                                                        "center",
                                                                }}
                                                            >
                                                                <Text>
                                                                    {balance}{" "}
                                                                </Text>
                                                                <View
                                                                    style={{
                                                                        justifyContent:
                                                                            "center",
                                                                        alignItems:
                                                                            "center",
                                                                    }}
                                                                >
                                                                    <Text
                                                                        style={{
                                                                            fontSize: 4.5, // Increased from 4
                                                                            lineHeight: 0, // Match font size
                                                                        }}
                                                                    >
                                                                        CR
                                                                    </Text>
                                                                </View>
                                                            </View>
                                                        </TD>
                                                    </TR>
                                                );
                                            })}
                                        </Table>
                                    </TD>
                                </TR>
                            </Table>
                            {pageIndex + 1 === totalPages ? (
                                <Table>
                                    <TH>
                                        <TD style={{ borderTop: 0 }}>
                                            <Table
                                                style={{ border: "0px" }}
                                                weightings={[
                                                    1.25, 1.25, 3.5, 3.5, 1.45,
                                                    1.45, 2,
                                                ]}
                                            >
                                                <TH>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 6,
                                                        }}
                                                    >
                                                        Grand Total
                                                    </TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 6,
                                                        }}
                                                    >
                                                        {totalDebit.toLocaleString(
                                                            "en-IN",
                                                            {
                                                                minimumFractionDigits: 2,
                                                                maximumFractionDigits: 2,
                                                            }
                                                        )}
                                                    </TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 6,
                                                        }}
                                                    >
                                                        {totalCredit.toLocaleString(
                                                            "en-IN",
                                                            {
                                                                minimumFractionDigits: 2,
                                                                maximumFractionDigits: 2,
                                                            }
                                                        )}
                                                    </TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                            paddingLeft: 6,
                                                        }}
                                                    ></TD>
                                                </TH>
                                            </Table>
                                        </TD>
                                    </TH>
                                    <TH>
                                        <TD style={{ borderTop: 0 }}>
                                            <Table
                                                style={{ border: "0px" }}
                                                weightings={[
                                                    1.25, 1.25, 3.5, 3.5, 1.45,
                                                    1.45, 2,
                                                ]}
                                            >
                                                <TH>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "center",
                                                            alignItems:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 6,
                                                        }}
                                                    >
                                                        Closing Balance
                                                    </TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 6,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 6,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingRight: 6,
                                                            paddingVertical: 4,
                                                        }}
                                                    >
                                                        <View
                                                            style={{
                                                                flexDirection:
                                                                    "row",
                                                                alignItems:
                                                                    "center",
                                                            }}
                                                        >
                                                            <Text
                                                                style={
                                                                    styles.bold
                                                                }
                                                            >
                                                                {Number(
                                                                    lastTransaction.balance.replace(
                                                                        /,/g,
                                                                        ""
                                                                    )
                                                                ).toLocaleString(
                                                                    "en-IN",
                                                                    {
                                                                        minimumFractionDigits: 2,
                                                                        maximumFractionDigits: 2,
                                                                    }
                                                                )}
                                                            </Text>
                                                            <View
                                                                style={{
                                                                    justifyContent:
                                                                        "center",
                                                                    alignItems:
                                                                        "center",
                                                                }}
                                                            >
                                                                <Text
                                                                    style={{
                                                                        fontSize: 4.5, // Increased from 4
                                                                        lineHeight: 0, // Match font size
                                                                    }}
                                                                >
                                                                    {" "}
                                                                    CR
                                                                </Text>
                                                            </View>
                                                        </View>
                                                    </TD>
                                                </TH>
                                            </Table>
                                        </TD>
                                    </TH>
                                    <TH>
                                        <TD
                                            style={{
                                                borderTop: 0,
                                                borderLeft: 0,
                                                borderRight: 0,
                                            }}
                                        >
                                            <Table
                                                style={{ border: "0px" }}
                                                weightings={[
                                                    1.25, 1.25, 3.5, 3.5, 1.45,
                                                    1.45, 2,
                                                ]}
                                            >
                                                <TH>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                            paddingLeft: 72,
                                                            paddingBottom: 25,
                                                        }}
                                                    >
                                                        Balance C/F
                                                    </TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingVertical: 3,
                                                        }}
                                                    ></TD>
                                                    <TD
                                                        style={{
                                                            justifyContent:
                                                                "flex-end",
                                                            alignItems:
                                                                "center",
                                                            paddingHorizontal: 1,
                                                            paddingRight: 6,
                                                            paddingVertical: 4,
                                                            paddingBottom: 25,
                                                        }}
                                                    >
                                                        <View
                                                            style={{
                                                                flexDirection:
                                                                    "row",
                                                                alignItems:
                                                                    "center",
                                                            }}
                                                        >
                                                            <Text
                                                                style={
                                                                    styles.bold
                                                                }
                                                            >
                                                                {Number(
                                                                    lastTransaction.balance.replace(
                                                                        /,/g,
                                                                        ""
                                                                    )
                                                                ).toLocaleString(
                                                                    "en-IN",
                                                                    {
                                                                        minimumFractionDigits: 2,
                                                                        maximumFractionDigits: 2,
                                                                    }
                                                                )}
                                                            </Text>
                                                            <View
                                                                style={{
                                                                    justifyContent:
                                                                        "center",
                                                                    alignItems:
                                                                        "center",
                                                                }}
                                                            >
                                                                <Text
                                                                    style={{
                                                                        fontSize: 4.5, // Increased from 4
                                                                        lineHeight: 0, // Match font size
                                                                    }}
                                                                >
                                                                    {" "}
                                                                    CR
                                                                </Text>
                                                            </View>
                                                        </View>
                                                    </TD>
                                                </TH>
                                            </Table>
                                        </TD>
                                    </TH>
                                    <TH>
                                        <TD
                                            style={{
                                                borderTop: 0,
                                                borderBottom: 0,
                                                borderLeft: 0,
                                                borderRight: 0,
                                                paddingTop: 8,
                                                justifyContent: "center",
                                            }}
                                        >
                                            <Text>
                                                ******* End of Report *******
                                            </Text>
                                        </TD>
                                    </TH>
                                </Table>
                            ) : (
                                <Table
                                    style={{ border: "0px" }}
                                    weightings={[
                                        1.25, 1.25, 3.5, 3.5, 1.45, 1.45, 2,
                                    ]}
                                >
                                    <TH>
                                        <TD
                                            style={{
                                                justifyContent: "center",
                                                paddingHorizontal: 1,
                                            }}
                                        ></TD>
                                        <TD
                                            style={{
                                                justifyContent: "center",
                                                paddingHorizontal: 1,
                                            }}
                                        ></TD>
                                        <TD
                                            style={{
                                                paddingHorizontal: 1,
                                            }}
                                        ></TD>
                                        <TD
                                            style={{
                                                justifyContent: "flex-end",
                                                paddingHorizontal: 2,
                                                paddingVertical: 1,
                                            }}
                                        >
                                            Total
                                        </TD>
                                        <TD
                                            style={{
                                                justifyContent: "flex-end",
                                                paddingHorizontal: 2,
                                                paddingVertical: 1,
                                            }}
                                        >
                                            {totalDebit.toLocaleString(
                                                "en-IN",
                                                {
                                                    minimumFractionDigits: 2,
                                                    maximumFractionDigits: 2,
                                                }
                                            )}
                                        </TD>
                                        <TD
                                            style={{
                                                justifyContent: "flex-end",
                                                paddingHorizontal: 2,
                                                paddingVertical: 1,
                                            }}
                                        >
                                            {totalCredit.toLocaleString(
                                                "en-IN",
                                                {
                                                    minimumFractionDigits: 2,
                                                    maximumFractionDigits: 2,
                                                }
                                            )}
                                        </TD>
                                        <TD
                                            style={{
                                                justifyContent: "flex-end",
                                                paddingHorizontal: 1,
                                                paddingLeft: 6,
                                            }}
                                        ></TD>
                                    </TH>
                                </Table>
                            )}

                            {/* Footer - Page Totals */}
                            <View style={styles.footer}>
                                <Text>
                                    Page {pageIndex + 1} of {totalPages}
                                </Text>
                            </View>
                        </PageWrapper>
                    </Page>
                );
            })}
        </Document>
    );
};

export default StatementPDF;
